server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://db:3306/cool?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.demos.entity
